### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by vkassingh** [curiouslearning/CuriousReaderRCC#1]
@burrage  
I would like to contribute to CuriousReaderRCC. Can you please guide me on this?

**Comment by bigdevlarry** [comment]
Here for the contribution too

**Comment by burrage** [comment]
Hi @vkassingh  and @LarrySul  ! Thanks for reaching out. If you could send an e-mail to jobs@curiouslearning.org with:

- Your resume
- Links to any portfolio pieces you have to showcase any technical writing you have written in the past
- [Optional]: Links to any pieces of shareable code/software you may have written that you have also documented

Again thanks for your interest and we look forward to hearing from you.
