### ISSUE TITLE
[GSoD'21] Curious Learning: Curious Reader Authoring Documentation

### ISSUE THREAD

**Issue by abhishek-iiit** [curiouslearning/CuriousReaderRCC#10]
Hello,
I am really excited to contribute to this year's GSoD project proposal. They are amazing and Interesting, and I believe they can be completed before a given time interval. I found them via a [GSoD](https://developers.google.com/season-of-docs/docs/participants) official website and previously from a season of doc [repo](https://github.com/abhishek-iiit/season-of-docs/blob/main/2021-participants/interested-organizations.md).

I have gone through all the requirements mentioned for this project on the [website](https://www.curiouslearning.org/season-of-docs-) along with the attached 3 attached doc [here](https://docs.google.com/document/d/1xp0MpWsMLokyiZFNQMhNDNsPHgqgXtxfmPJoB8lmtXI/edit), [here](https://docs.google.com/document/d/1kxV4OSAxZJeetDxGWdOt46pPn3qDN-juHL-RSagCgwA/edit), [here](https://docs.google.com/document/d/1f4g7eTH_dTFaln6cNxH79Nr4yzNLWX6ExSqef0Y1H58/edit) . I have been passionately writing tutorials, blogs, reviews about open-source projects. Gone through the problem statement and the scope, I believe I have got some idea of how to proceed with it.

You can find my previous work at [medium](https://abhishek-iiit.medium.com/), [hashnode](https://abhishek-iiit.hashnode.dev/). I would give my best to achieve this goal.
Could you please provide my some more reference, so that I may get into depth in this project. Any feedback and suggestion are most welcome.

**Comment by Shubhamlmp** [comment]
Hello Dear @burrage I am interested in working on this project as a technical writer.
I would be grateful if you can tell me if there's anything else that I could do which would be appreciated. Any further guidance or inputs would certainly be of great help.

**Comment by burrage** [comment]
Hi @abhishek-iiit  and @Shubhamlmp  ! Thanks for reaching out. If you could send an e-mail to jobs@curiouslearning.org with:

- Your resume
- Links to any portfolio pieces you have to showcase any technical writing you have written in the past
- [Optional]: Links to any pieces of shareable code/software you may have written that you have also documented

Again thanks for your interest and we look forward to hearing from you.
