### ISSUE TITLE
[Introduction] Introducing myself

### ISSUE THREAD

**Issue by atharvashirdhankar** [curiouslearning/CuriousReaderRCC#11]
Hello Everyone , Myself Atharva . I m BSc CS student from Patkar Varde College Mumbai. I m also active open source contributer , technical writer and also a new technologies learning enthusiast .
Surely looking forward to work as a GSoD 2021 student for Curious Learning.

I have readed the points mentioned on the Curious Learning  GSoD webpage. And understood the requirements needed to participate in GSoD.
Completely agreed to those points because those are the basic requirements one should need for Contribution.
And I would like to work on eBook creator Documentation for GSoD this year with curious learning team.

Here is my GitHub id :
https://github.com/StarTrooper08

Thank you.

**Comment by esticojerry** [comment]
Hello my name is Osayande Esther from Nigeria. I am an intern with Early Days Montessori school. I love teaching kids. Am  interested in Early year education hence i want to participate in this particular project, though new to open source project, but will like to kick start my open source career  with this project.  I would love to work on eBook creator Documentation with GSoD this year with Curious learning team.
Thank you.

**Comment by burrage** [comment]
Hi @StarTrooper08 and @esticojerry ! Thanks for reaching out. If you could send an e-mail to jobs@curiouslearning.org with:

- Your resume
- Links to any portfolio pieces you have to showcase any technical writing you have written in the past
- [Optional]: Links to any pieces of shareable code/software you may have written that you have also documented

Again thanks for your interest and we look forward to hearing from you.

**Comment by esticojerry** [comment]
Hi,
Thanks for reaching out to me. I have completed my resume for this project.
Could you please help me to review it before i send it to
***@***.***
Please find attached the proposal below.
Thanks.
