### ISSUE TITLE
Google Season of Docs

### ISSUE THREAD

**Issue by manthanguptaa** [curiouslearning/CuriousReaderRCC#2]
Hey There!

I have gone through the whole doc, and I love what you are doing at Curious Learning, and it resonated with me well. I even tried out the English version of the application, and I completely love it! You have developed the application in many different languages that is quite wonderful.

That said, I would love to help Curious Learning as a Technical Writer and be an integral part of the organization. Let's make it easier for these kids to learn new things in every possible way.

Talking about my experience, I write blogs on Medium that has till now garnered 10,000+ views from across the globe, and the feedback that I receive for them is that they are well structured, concise, and easily readable. While writing blogs, I structure them in a way so that even a 10yr old kid can read them easily. I also often write candid pieces on my LinkedIn profile that you can check out too.

[Medium](https://medium.com/@manthangupta109)
[LinkedIn](https://www.linkedin.com/in/manthangupta109/)
[GitHub](https://github.com/Manthan109)

I look forward to working on this amazing project!

**Comment by burrage** [comment]
Hi @Manthan109  ! Thanks for reaching out. If you could send an e-mail to jobs@curiouslearning.org with:

- Your resume
- Links to any portfolio pieces you have to showcase any technical writing you have written in the past
- [Optional]: Links to any pieces of shareable code/software you may have written that you have also documented

Again thanks for your interest and we look forward to hearing from you.

**Comment by manthanguptaa** [comment]
I have sent the email! I look forward to the prompt reply and the opportunity to work with Curious Learning in doing something bigger that creates an impact in someone's life!
