### ISSUE TITLE
Interested in Google season of docs

### ISSUE THREAD

**Issue by AryanSethi** [curiouslearning/CuriousReaderRCC#3]
I'm highly interested in CuriousReader GSOD project and would like to communicate with the mentors.
Can I have their contacts ?

**Comment by burrage** [comment]
Hi @AryanSethi  ! Thanks for reaching out. If you could send an e-mail to jobs@curiouslearning.org with:

- Your resume
- Links to any portfolio pieces you have to showcase any technical writing you have written in the past
- [Optional]: Links to any pieces of shareable code/software you may have written that you have also documented

Again thanks for your interest and we look forward to hearing from you.
