### ISSUE TITLE
INTERESTED AS TECHNICAL WRITER AT CURIOUS READER

### ISSUE THREAD

**Issue by shraddhavp** [curiouslearning/CuriousReaderRCC#4]
Want to participate in curious reader as a technical writer as a part of gsod 2021?
Can you please provide me the contact?
My experience :

1. I am a software engineer at American Express 
2. have written couple of blogs on Medium
3. Have served as a Technical content writer at Girlscript foundation
4. Have been a top contributor in Hackincodes and girlscript summer of code open source contribution programs
https://www.linkedin.com/in/shraddha-v-prasad/ - Linkedin
https://github.com/shraddhavp - Github
https://medium.com/@anitha.shraddha - Medium

I am really interested in this project can you please provide me the details ?

**Comment by burrage** [comment]
Hi @shraddhavp  ! Thanks for reaching out. If you could send an e-mail to jobs@curiouslearning.org with:

- Your resume
- Links to any portfolio pieces you have to showcase any technical writing you have written in the past
- [Optional]: Links to any pieces of shareable code/software you may have written that you have also documented

Again thanks for your interest and we look forward to hearing from you.

**Comment by shraddhavp** [comment]
Hello Sir,
By when can we expect the results sir ?
*BY :*
*Shraddha Prasad*

**Comment by burrage** [comment]
Hi @shraddhavp !

If you have been selected for an interview, you'll be hearing back via e-mail. Good luck!
