### ISSUE TITLE
Interested to contribute 

### ISSUE THREAD

**Issue by Surajv311** [curiouslearning/CuriousReaderRCC#5]
I would like to contribute to the GSOD project as a Technical Writer.
I've read the google docs and I'm excited to contribute to the project!
Could you please fill me up with the contact details?

Blogging profiles: 
- [Hashnode](https://surajv.hashnode.dev/)
- [Medium](https://surajsv.medium.com/)

Professional profiles: 
- [Linkedin](https://www.linkedin.com/in/surajverma-sv/)
- [Github](https://github.com/surajv311)

**Comment by burrage** [comment]
Hi @Surajv311  ! Thanks for reaching out. If you could send an e-mail to jobs@curiouslearning.org with:

- Your resume
- Links to any portfolio pieces you have to showcase any technical writing you have written in the past
- [Optional]: Links to any pieces of shareable code/software you may have written that you have also documented

Again thanks for your interest and we look forward to hearing from you.
