### ISSUE TITLE
Requesting some help to get started.

### ISSUE THREAD

**Issue by verma16Ayush** [curiouslearning/CuriousReaderRCC#6]
Hello, this is Ayush.
I would love to write docs for you guys but, Excuse me if this is a dumb request, I am having trouble getting started with your project so if you could just point me in the right direction, it would be really awesome. Quite new to OSS.

**Comment by burrage** [comment]
Hi @verma16Ayush  ! Thanks for reaching out. If you could send an e-mail to jobs@curiouslearning.org with:

- Your resume
- Links to any portfolio pieces you have to showcase any technical writing you have written in the past
- [Optional]: Links to any pieces of shareable code/software you may have written that you have also documented

Again thanks for your interest and we look forward to hearing from you.

**Comment by verma16Ayush** [comment]
Hello @burrage 
I had sent in the mail along with a request to have some discussion with the mentors related to project ideas and get a more concrete expectation of what the project is about. I have not received any response since. I turned in my Statement of Interest yesterday to jobs@curiouslearning.org anyway since the last date to hire writers is just a day away now. please let me know if you have already filled in the position or if there is anything else I can do to ensure a positive response from your organisation.
